[package]
name = "fatr"
version = "0.3.0"
authors = ["Zane Sterling <sterling.zane@gmail.com>", "Alex Von Gluck IV <kallisti5@unixzen.com>"]
description = "A tool for manipulating FAT12,FAT16,FAT32 images."
license = "MIT"

[dependencies]
itertools = "0.5.9"
byteorder = "*"
